title: "tv typography "
description: The difference between the typography used in different form of TV
footer_text: Copyright 2021 Lucy Ware
header_feature_image: ../uploads/istockphoto-1215833412-170667a.jpg
header_text: TV TYPOGRAPHY
header_text_color: "#effbfb"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/tv-typography-logo.jpg
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: false
